#+export_file_name: README
* Osmacs

* Sobre este repositorio
Emacs es mi editor de texto preferido y este repositorio esta toda su configuracion. Cabe resaltar que este repositorio coge muchas lineas de codigo de muchas configuraciones externas que acomode a mi manejo lo cual agradezco a todas esas personas que hacen esto posible a los Hacker de emacs.
* StartUp
** Lexical Binding
Uso lexical-binding. [[https://nullprogram.com/blog/2016/12/22/][Why?]]
#+begin_quote
Until Emacs 24.1 (June 2012), Elisp only had dynamically scoped variables, a feature, mostly by accident, common to old lisp dialects. While dynamic scope has some selective uses, it’s widely regarded as a mistake for local variables, and virtually no other languages have adopted it.
#+end_quote
#+include: "init.el" src emacs-lisp :lines "1-2"
* Package Manager
Cuando comence a usar emacs quise extender las funcionalidades para ello utilice los repositorios de [[https://melpa.org/][MELPA]] con ayuda del paquete [[https://github.com/jwiegley/use-package][use-package]] pero luego descubri [[https://github.com/radian-software/straight.el][straight.el]], un gestor de paquetes puramente funcional para la nueva generacion de hackers de emacs, me gusto mas porque no descargaba el paquete en si sino clonaba el repositorio y me permitia hacer modificaciones directas al repositorio descargado.

Para añadirlo Straight.el
#+include: "elisp/init-package.el" src emacs-lisp :range-begin "BootstrapStraight" :range-end "-BootstrapStraight" :lines "4-20"
** Use-package
Instalar y configurar use-package
#+include: "elisp/init-package.el" src emacs-lisp :range-begin "ConfigureUsePackage" :range-end "-ConfigureUsePackage" :lines "23-42"
*** Diminish
[[https://github.com/emacsmirror/diminish][Diminish]], una característica que elimina ciertos modos menores de la línea de modo.
#+include: "elisp/init-package.el" src emacs-lisp :range-begin "Diminish" :range-end "-Diminish" :lines "47-48"
* Global Functionalities
** USer Information
*Prerequisite*:Informacion basica del usuario
#+include: "elisp/init-const.el" src emacs-lisp :range-begin "UserInfo" :rage-end "-UserInfo" :lines "4-7"
** UTF8 for windows
#+include: "elisp/init-global-config.el" src emacs-lisp :range-begin "UTF8Coding" :rage-end "-UTF8Coding" :lines "16-27"
** Bindings
#+include: "elisp/init-global-config.el" src emacs-lisp :range-begin "DefineBindings" :rage-end "-DefiBindings" :lines "12-13"
* Package Basics
** Search
*** Avy
[[https://github.com/abo-abo/avy][Avy]], una de las mejores herramientas para moverte en el texto.
#+include: "elisp/init-search.el" src emacs-lisp :range-begin "Avy" :range-end "-Avy" :lines "7-17"
*** CtrlF
El paquete **[[https://github.com/radian-software/ctrlf][ctrlf]]**  proporciona un reemplazo para 'buscar' que es más similar a las interfaces de búsqueda de texto probadas y verdaderas en la web navegadores y otros programas (piense en lo que sucede cuando escribe ctrl + F).
#+include: "elisp/init-search.el" src emacs-lisp :range-begin "CtrlF" :range-end "-CtrlF" :lines "7-10"
